CREATE DATABASE HEALTHMED;

-------------------------------------------------------------

CREATE TABLE [MEDIC](
[UID] [uniqueidentifier] NOT NULL DEFAULT NEWID(),
[CRM] [VARCHAR] (10),
[NAME] [VARCHAR] (100) NOT NULL,
[SPECIALTY] [VARCHAR] (100) NOT NULL,
[PASSWORD] [VARCHAR] (50) NOT NULL
);

ALTER TABLE [MEDIC] ALTER COLUMN [UID] [uniqueidentifier] NOT NULL;
ALTER TABLE [MEDIC] ADD CONSTRAINT PK_MEDIC
PRIMARY KEY CLUSTERED ([UID]);

--------------------------------------------------------------

CREATE TABLE [PATIENT](
[UID] [uniqueidentifier] NOT NULL DEFAULT NEWID(),
[CPF] [VARCHAR] (11),
[NAME] [VARCHAR] (100) NOT NULL,
[EMAIL] [VARCHAR] (150) NOT NULL,
[PASSWORD] [VARCHAR] (50) NOT NULL

);
ALTER TABLE [PATIENT] ALTER COLUMN [UID] [uniqueidentifier] NOT NULL;
ALTER TABLE [PATIENT] ADD CONSTRAINT PK_PATIENT
PRIMARY KEY CLUSTERED ([UID]);

--------------------------------------------------------------


CREATE TABLE [SCHEDULE](
[UID] [uniqueidentifier] NOT NULL DEFAULT NEWID(),
[STARTSAT] [DATETIME] NOT NULL,
[ENDSAT] [DATETIME] NOT NULL,
[PRICE] [MONEY],
[APPROVED] [BIT],
[MEDICUID] [uniqueidentifier] NOT NULL,
[PATIENTUID] [uniqueidentifier],
CONSTRAINT PK_SCHEDULE
PRIMARY KEY CLUSTERED ([UID]),
CONSTRAINT FK_MEDIC FOREIGN KEY (MEDICUID)
REFERENCES MEDIC([UID]),
CONSTRAINT FK_PATIENT FOREIGN KEY (PATIENTUID)
REFERENCES PATIENT([UID])
);

CREATE TABLE [dbo].[CANCELEDSCHEDULES](
	[SCHEDULEUID] uniqueidentifier NOT NULL,
	[PATIENTUID] uniqueidentifier NOT NULL,
	[REASON] VARCHAR(400) NOT NULL,
CONSTRAINT [FK_PATIENT_CANCELED] FOREIGN KEY([PATIENTUID])
REFERENCES [dbo].[PATIENT] ([UID]),
CONSTRAINT [FK_SCHEDULE_CANCELED] FOREIGN KEY([SCHEDULEUID])
REFERENCES [dbo].[SCHEDULE] ([UID])

)
